services:
  agora-database:
    image: mariadb:latest
    container_name: agora-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: agora_db
      MYSQL_USER: agora
      MYSQL_PASSWORD: 123456

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb:/etc/mysql/conf.d

volumes:
  mariadb_data: